import CodexCore
import XCTest

final class ConfigLockfileTests: XCTestCase {
    func testReadConfigLockfileParsesRustShapeAndMetadata() throws {
        let dir = try ConfigLockfileTemporaryDirectory()
        let lockPath = dir.url.appendingPathComponent("session.config.lock.toml")
        try """
        version = 1
        codex_version = "0.1.0"

        [config]
        model = "gpt-5.1-codex-max"

        [config.debug.config_lockfile]
        load_path = "/tmp/old.lock.toml"
        """.write(to: lockPath, atomically: true, encoding: .utf8)

        let lockfile = try ConfigLockfileStore.readConfigLockfile(from: lockPath.path)

        XCTAssertEqual(lockfile.version, 1)
        XCTAssertEqual(lockfile.codexVersion, "0.1.0")
        let expectedConfig: ConfigValue = .table([
            "model": .string("gpt-5.1-codex-max"),
            "debug": .table([
                "config_lockfile": .table([
                    "load_path": .string("/tmp/old.lock.toml")
                ])
            ])
        ])
        XCTAssertEqual(lockfile.config, expectedConfig)
    }

    func testRenderConfigLockfileUsesRustTopLevelOrder() throws {
        let lockfile = ConfigLockfile(
            version: 1,
            codexVersion: #"0.1."quoted""#,
            config: .table([
                "model": .string("gpt-5.1-codex-max"),
                "approval_policy": .string("on-failure")
            ])
        )

        XCTAssertEqual(ConfigLockfileStore.renderConfigLockfile(lockfile), #"""
        version = 1
        codex_version = "0.1.\"quoted\""

        [config]
        approval_policy = "on-failure"
        model = "gpt-5.1-codex-max"
        """# + "\n")
    }

    func testExportConfigLockfileWritesRustPathAndCreatesDirectory() throws {
        let dir = try ConfigLockfileTemporaryDirectory()
        let exportDir = dir.url.appendingPathComponent("locks", isDirectory: true)
        let threadID = try ThreadId(string: "00000000-0000-4000-8000-000000000123")
        let lockfile = ConfigLockfile(
            version: 1,
            codexVersion: "0.1.0",
            config: .table(["model": .string("gpt-5.1-codex-max")])
        )

        let path = try ConfigLockfileStore.exportConfigLockfile(
            lockfile,
            to: exportDir,
            threadID: threadID
        )

        XCTAssertEqual(path.lastPathComponent, "\(threadID).config.lock.toml")
        XCTAssertTrue(FileManager.default.fileExists(atPath: path.path))
        XCTAssertEqual(try ConfigLockfileStore.readConfigLockfile(from: path.path), lockfile)
        XCTAssertEqual(try String(contentsOf: path, encoding: .utf8), #"""
        version = 1
        codex_version = "0.1.0"

        [config]
        model = "gpt-5.1-codex-max"
        """# + "\n")
    }

    func testConfigWithoutLockControlsRemovesEmptyDebugTableLikeRust() {
        let config: ConfigValue = .table([
            "model": .string("gpt-5.1-codex-max"),
            "debug": .table([
                "config_lockfile": .table([
                    "load_path": .string("/tmp/old.lock.toml")
                ])
            ])
        ])

        XCTAssertEqual(
            ConfigLockfileStore.configWithoutLockControls(config),
            .table(["model": .string("gpt-5.1-codex-max")])
        )
    }

    func testValidateConfigLockReplayRejectsVersionMismatchByDefaultLikeRust() throws {
        let expected = ConfigLockfile(
            version: 1,
            codexVersion: "0.1.0",
            config: .table(["model": .string("gpt-5.1-codex-max")])
        )
        let actual = ConfigLockfile(
            version: 1,
            codexVersion: "0.2.0",
            config: .table(["model": .string("gpt-5.1-codex-max")])
        )

        XCTAssertThrowsError(try ConfigLockfileStore.validateConfigLockReplay(
            expectedLock: expected,
            actualLock: actual
        )) { error in
            XCTAssertEqual(
                String(describing: error),
                "config lock Codex version mismatch: lock was generated by 0.1.0, current version is 0.2.0; set debug.config_lockfile.allow_codex_version_mismatch=true to ignore this"
            )
        }
    }

    func testValidateConfigLockReplayCanIgnoreVersionMismatchLikeRust() throws {
        let expected = ConfigLockfile(
            version: 1,
            codexVersion: "0.1.0",
            config: .table([
                "model": .string("gpt-5.1-codex-max"),
                "debug": .table([
                    "config_lockfile": .table(["load_path": .string("/tmp/old.lock.toml")])
                ])
            ])
        )
        let actual = ConfigLockfile(
            version: 1,
            codexVersion: "0.2.0",
            config: .table(["model": .string("gpt-5.1-codex-max")])
        )

        XCTAssertNoThrow(try ConfigLockfileStore.validateConfigLockReplay(
            expectedLock: expected,
            actualLock: actual,
            options: ConfigLockReplayOptions(allowCodexVersionMismatch: true)
        ))
    }

    func testValidateConfigLockReplayReportsConfigDiffLikeRust() throws {
        let expected = ConfigLockfile(
            version: 1,
            codexVersion: "0.1.0",
            config: .table(["model": .string("gpt-5.1-codex-max")])
        )
        let actual = ConfigLockfile(
            version: 1,
            codexVersion: "0.1.0",
            config: .table(["model": .string("gpt-5.1-codex-mini")])
        )

        XCTAssertThrowsError(try ConfigLockfileStore.validateConfigLockReplay(
            expectedLock: expected,
            actualLock: actual
        )) { error in
            let message = String(describing: error)
            XCTAssertTrue(message.contains("replayed effective config does not match config lock"))
            XCTAssertTrue(message.contains(#"-model = "gpt-5.1-codex-max""#))
            XCTAssertTrue(message.contains(#"+model = "gpt-5.1-codex-mini""#))
        }
    }

    func testReadConfigLockfileRejectsUnsupportedVersionLikeRust() throws {
        let dir = try ConfigLockfileTemporaryDirectory()
        let lockPath = dir.url.appendingPathComponent("session.config.lock.toml")
        try """
        version = 2
        codex_version = "0.1.0"

        [config]
        """.write(to: lockPath, atomically: true, encoding: .utf8)

        XCTAssertThrowsError(try ConfigLockfileStore.readConfigLockfile(from: lockPath.path)) { error in
            XCTAssertTrue(
                String(describing: error).contains("unsupported config lock version 2; expected 1")
            )
        }
    }
}

private final class ConfigLockfileTemporaryDirectory {
    let url: URL

    init() throws {
        url = FileManager.default.temporaryDirectory
            .appendingPathComponent("codex-config-lockfile-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
    }

    deinit {
        try? FileManager.default.removeItem(at: url)
    }
}
