@testable import CodexMCPServer
import Foundation
import XCTest

final class CodexMCPServerTests: XCTestCase {
    func testInitializePingAndListToolsResponses() async throws {
        var state = CodexMCPServerState()

        let initialize = try await response(
            for: #"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","clientInfo":{"name":"test","version":"0"}}}"#,
            state: &state
        )
        XCTAssertEqual(initialize["jsonrpc"] as? String, "2.0")
        XCTAssertEqual(initialize["id"] as? Int, 1)
        let initializeResult = try XCTUnwrap(initialize["result"] as? [String: Any])
        XCTAssertEqual(initializeResult["protocolVersion"] as? String, "2025-06-18")
        let serverInfo = try XCTUnwrap(initializeResult["serverInfo"] as? [String: Any])
        XCTAssertEqual(serverInfo["name"] as? String, "codex-mcp-server")
        XCTAssertEqual(serverInfo["title"] as? String, "Codex")
        XCTAssertEqual(serverInfo["version"] as? String, "0.0.0")
        let userAgent = try XCTUnwrap(serverInfo["userAgent"] as? String)
        XCTAssertTrue(userAgent.hasPrefix("codex_swift/0.0.0 "))
        XCTAssertTrue(userAgent.hasSuffix(" (test; 0)"))
        let capabilities = try XCTUnwrap(initializeResult["capabilities"] as? [String: Any])
        let toolsCapability = try XCTUnwrap(capabilities["tools"] as? [String: Any])
        XCTAssertEqual(toolsCapability["listChanged"] as? Bool, true)

        let ping = try await response(for: #"{"jsonrpc":"2.0","id":"p","method":"ping","params":{}}"#, state: &state)
        XCTAssertEqual(ping["id"] as? String, "p")
        XCTAssertNotNil(ping["result"] as? [String: Any])

        let tools = try await response(for: #"{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}"#, state: &state)
        let toolsResult = try XCTUnwrap(tools["result"] as? [String: Any])
        let toolRows = try XCTUnwrap(toolsResult["tools"] as? [[String: Any]])
        XCTAssertEqual(toolRows.compactMap { $0["name"] as? String }, ["codex", "codex-reply"])
        let codexTool = toolRows[0]
        XCTAssertEqual(codexTool["title"] as? String, "Codex")
        let inputSchema = try XCTUnwrap(codexTool["inputSchema"] as? [String: Any])
        XCTAssertEqual(inputSchema["required"] as? [String], ["prompt"])
        let properties = try XCTUnwrap(inputSchema["properties"] as? [String: [String: Any]])
        XCTAssertEqual(
            properties["approval-policy"]?["description"] as? String,
            "Approval policy for shell commands generated by the model: `untrusted`, `on-failure`, `on-request`, `never`."
        )
        XCTAssertEqual(properties["approval-policy"]?["enum"] as? [String], [
            "untrusted",
            "on-failure",
            "on-request",
            "never"
        ])
        XCTAssertEqual(
            properties["config"]?["description"] as? String,
            "Individual config settings that will override what is in CODEX_HOME/config.toml."
        )
        XCTAssertEqual(properties["config"]?["additionalProperties"] as? Bool, true)
        XCTAssertEqual(
            properties["developer-instructions"]?["description"] as? String,
            "Developer instructions that should be injected as a developer role message."
        )

        let replyTool = toolRows[1]
        XCTAssertEqual(replyTool["description"] as? String, "Continue a Codex conversation by providing the thread id and prompt.")
        let replySchema = try XCTUnwrap(replyTool["inputSchema"] as? [String: Any])
        XCTAssertEqual(replySchema["required"] as? [String], ["prompt"])
        let outputSchema = try XCTUnwrap(replyTool["outputSchema"] as? [String: Any])
        XCTAssertEqual(outputSchema["required"] as? [String], ["threadId", "content"])
        let replyProperties = try XCTUnwrap(replySchema["properties"] as? [String: [String: Any]])
        XCTAssertEqual(
            replyProperties["conversationId"]?["description"] as? String,
            "DEPRECATED: use threadId instead."
        )
        XCTAssertEqual(
            replyProperties["threadId"]?["description"] as? String,
            "The thread id for this Codex session. This field is required, but we keep it optional here for backward compatibility for clients that still use conversationId."
        )
        XCTAssertEqual(
            replyProperties["prompt"]?["description"] as? String,
            "The *next user prompt* to continue the Codex conversation."
        )
    }

    func testCodexToolCallDecodesArgumentsAndReturnsTextContent() async throws {
        var state = CodexMCPServerState()
        let receivedCall = CallCapture()

        let message = """
        {"jsonrpc":"2.0","id":7,"method":"tools/call","params":{"name":"codex","arguments":{"prompt":"ship it","model":"gpt-5","profile":"work","cwd":"/tmp/work","approval-policy":"never","sandbox":"workspace-write","config":{"model_reasoning_effort":"high"},"base-instructions":"base","developer-instructions":"dev","compact-prompt":"compact"}}}
        """
        let result = try await response(
            for: message,
            state: &state,
            codexToolRunner: { call in
                await receivedCall.set(call)
                return CodexMCPToolResult(text: "done", threadID: "123e4567-e89b-12d3-a456-426614174001")
            }
        )

        let capturedCall = await receivedCall.value
        XCTAssertEqual(capturedCall, CodexMCPToolCall(
            prompt: "ship it",
            model: "gpt-5",
            profile: "work",
            cwd: "/tmp/work",
            approvalPolicy: "never",
            sandbox: "workspace-write",
            config: ["model_reasoning_effort": .string("high")],
            baseInstructions: "base",
            developerInstructions: "dev",
            compactPrompt: "compact"
        ))
        let content = try textContent(from: result)
        XCTAssertEqual(content.text, "done")
        XCTAssertFalse(content.isError)
        let structuredContent = try structuredContent(from: result)
        XCTAssertEqual(structuredContent["threadId"] as? String, "123e4567-e89b-12d3-a456-426614174001")
        XCTAssertEqual(structuredContent["content"] as? String, "done")
    }

    func testCodexToolCallReportsMissingPromptAsToolError() async throws {
        var state = CodexMCPServerState()

        let result = try await response(
            for: #"{"jsonrpc":"2.0","id":8,"method":"tools/call","params":{"name":"codex","arguments":{"model":"gpt-5"}}}"#,
            state: &state,
            codexToolRunner: { _ in
                XCTFail("runner should not be called when prompt is missing")
                return CodexMCPToolResult(text: "unused")
            }
        )

        let content = try textContent(from: result)
        XCTAssertEqual(content.text, "Missing arguments for codex tool-call; the `prompt` field is required.")
        XCTAssertTrue(content.isError)
    }

    func testCodexReplyToolCallDecodesArgumentsAndReturnsTextContent() async throws {
        var state = CodexMCPServerState()
        let receivedReply = ReplyCapture()

        let result = try await response(
            for: #"{"jsonrpc":"2.0","id":9,"method":"tools/call","params":{"name":"codex-reply","arguments":{"threadId":"123e4567-e89b-12d3-a456-426614174000","prompt":"continue"}}}"#,
            state: &state,
            codexReplyRunner: { reply in
                await receivedReply.set(reply)
                return CodexMCPToolResult(text: "continued", threadID: reply.threadID)
            }
        )

        let capturedReply = await receivedReply.value
        XCTAssertEqual(capturedReply, CodexMCPToolReply(
            threadID: "123e4567-e89b-12d3-a456-426614174000",
            prompt: "continue"
        ))
        let content = try textContent(from: result)
        XCTAssertEqual(content.text, "continued")
        XCTAssertFalse(content.isError)
        let structuredContent = try structuredContent(from: result)
        XCTAssertEqual(structuredContent["threadId"] as? String, "123e4567-e89b-12d3-a456-426614174000")
        XCTAssertEqual(structuredContent["content"] as? String, "continued")
    }

    func testCodexReplyToolStillAcceptsDeprecatedConversationId() async throws {
        var state = CodexMCPServerState()
        let receivedReply = ReplyCapture()

        _ = try await response(
            for: #"{"jsonrpc":"2.0","id":9,"method":"tools/call","params":{"name":"codex-reply","arguments":{"conversationId":"123e4567-e89b-12d3-a456-426614174000","prompt":"continue"}}}"#,
            state: &state,
            codexReplyRunner: { reply in
                await receivedReply.set(reply)
                return CodexMCPToolResult(text: "continued")
            }
        )

        let capturedReply = await receivedReply.value
        XCTAssertEqual(capturedReply?.threadID, "123e4567-e89b-12d3-a456-426614174000")
        XCTAssertEqual(capturedReply?.conversationID, "123e4567-e89b-12d3-a456-426614174000")
    }

    func testCodexReplyToolReportsMissingArgumentsAsToolError() async throws {
        var state = CodexMCPServerState()

        let result = try await response(
            for: #"{"jsonrpc":"2.0","id":10,"method":"tools/call","params":{"name":"codex-reply","arguments":{"prompt":"continue"}}}"#,
            state: &state,
            codexReplyRunner: { _ in
                XCTFail("reply runner should not be called when threadId is missing")
                return CodexMCPToolResult(text: "unused")
            }
        )

        let content = try textContent(from: result)
        XCTAssertEqual(content.text, "Failed to parse thread_id: either threadId or conversationId must be provided")
        XCTAssertTrue(content.isError)
    }

    func testCodexReplyToolReportsMissingArgumentsLikeRust() async throws {
        var state = CodexMCPServerState()

        let result = try await response(
            for: #"{"jsonrpc":"2.0","id":10,"method":"tools/call","params":{"name":"codex-reply"}}"#,
            state: &state,
            codexReplyRunner: { _ in
                XCTFail("reply runner should not be called when arguments are missing")
                return CodexMCPToolResult(text: "unused")
            }
        )

        let content = try textContent(from: result)
        XCTAssertEqual(content.text, "Missing arguments for codex-reply tool-call; the `thread_id` and `prompt` fields are required.")
        XCTAssertTrue(content.isError)
    }

    private func response(
        for line: String,
        state: inout CodexMCPServerState,
        codexToolRunner: @escaping CodexMCPServer.CodexToolRunner = { _ in CodexMCPToolResult(text: "") },
        codexReplyRunner: CodexMCPServer.CodexReplyRunner? = nil
    ) async throws -> [String: Any] {
        let output = await CodexMCPServer.processLine(
            Data(line.utf8),
            state: &state,
            codexToolRunner: codexToolRunner,
            codexReplyRunner: codexReplyRunner
        )
        XCTAssertEqual(output.count, 1)
        return try XCTUnwrap(JSONSerialization.jsonObject(with: output[0]) as? [String: Any])
    }

    private func textContent(from response: [String: Any]) throws -> (text: String, isError: Bool) {
        let result = try XCTUnwrap(response["result"] as? [String: Any])
        let content = try XCTUnwrap(result["content"] as? [[String: Any]])
        let text = try XCTUnwrap(content.first?["text"] as? String)
        return (text, result["isError"] as? Bool ?? false)
    }

    private func structuredContent(from response: [String: Any]) throws -> [String: Any] {
        let result = try XCTUnwrap(response["result"] as? [String: Any])
        return try XCTUnwrap(result["structuredContent"] as? [String: Any])
    }
}

private actor CallCapture {
    var value: CodexMCPToolCall?

    func set(_ value: CodexMCPToolCall) {
        self.value = value
    }
}

private actor ReplyCapture {
    var value: CodexMCPToolReply?

    func set(_ value: CodexMCPToolReply) {
        self.value = value
    }
}
