import Foundation

public let configLockfileVersion = 1

public struct ConfigLockReplayOptions: Equatable, Sendable {
    public var allowCodexVersionMismatch: Bool

    public init(allowCodexVersionMismatch: Bool = false) {
        self.allowCodexVersionMismatch = allowCodexVersionMismatch
    }
}

public struct ConfigLockfile: Equatable, Sendable {
    public var version: Int
    public var codexVersion: String
    public var config: ConfigValue

    public init(version: Int = configLockfileVersion, codexVersion: String, config: ConfigValue) {
        self.version = version
        self.codexVersion = codexVersion
        self.config = config
    }

    public static func current(config: ConfigValue, codexVersion: String = "0.0.0") -> ConfigLockfile {
        ConfigLockfile(
            version: configLockfileVersion,
            codexVersion: codexVersion,
            config: config
        )
    }
}

public enum ConfigLockfileError: Error, Equatable, CustomStringConvertible, Sendable {
    case invalidLockfile(String)

    public var description: String {
        switch self {
        case let .invalidLockfile(message):
            return message
        }
    }
}

public enum ConfigLockfileStore {
    public static func readConfigLockfile(from path: String, fileManager: FileManager = .default) throws -> ConfigLockfile {
        let contents: String
        do {
            contents = try String(contentsOfFile: path, encoding: .utf8)
        } catch {
            throw ConfigLockfileError.invalidLockfile(
                "failed to read config lock file \(path): \(error)"
            )
        }

        let lockfile: ConfigLockfile
        do {
            lockfile = try parseConfigLockfile(contents)
        } catch let error as ConfigLockfileError {
            throw ConfigLockfileError.invalidLockfile(
                "failed to parse config lock file \(path): \(error.description)"
            )
        } catch {
            throw ConfigLockfileError.invalidLockfile(
                "failed to parse config lock file \(path): \(error)"
            )
        }
        try validateMetadataShape(lockfile)
        return lockfile
    }

    public static func parseConfigLockfile(_ contents: String) throws -> ConfigLockfile {
        guard case let .table(root) = try ConfigTomlParser.parse(contents) else {
            throw ConfigLockfileError.invalidLockfile("config lock root must be a table")
        }

        let allowedKeys: Set<String> = ["version", "codex_version", "config"]
        if let unknown = root.keys.sorted().first(where: { !allowedKeys.contains($0) }) {
            throw ConfigLockfileError.invalidLockfile("unknown config lock field \(unknown)")
        }

        guard case let .integer(version)? = root["version"] else {
            throw ConfigLockfileError.invalidLockfile("config lock version must be an integer")
        }
        guard let intVersion = Int(exactly: version) else {
            throw ConfigLockfileError.invalidLockfile("config lock version must fit in an Int")
        }
        guard case let .string(codexVersion)? = root["codex_version"] else {
            throw ConfigLockfileError.invalidLockfile("config lock codex_version must be a string")
        }
        guard case let .table(config)? = root["config"] else {
            throw ConfigLockfileError.invalidLockfile("config lock config must be a table")
        }

        return ConfigLockfile(
            version: intVersion,
            codexVersion: codexVersion,
            config: .table(config)
        )
    }

    public static func validateConfigLockReplay(
        expectedLock: ConfigLockfile,
        actualLock: ConfigLockfile,
        options: ConfigLockReplayOptions = ConfigLockReplayOptions()
    ) throws {
        try validateMetadataShape(expectedLock)
        try validateMetadataShape(actualLock)

        if !options.allowCodexVersionMismatch,
           expectedLock.codexVersion != actualLock.codexVersion
        {
            throw ConfigLockfileError.invalidLockfile(
                "config lock Codex version mismatch: lock was generated by \(expectedLock.codexVersion), current version is \(actualLock.codexVersion); set debug.config_lockfile.allow_codex_version_mismatch=true to ignore this"
            )
        }

        let expected = lockfileForComparison(expectedLock, options: options)
        let actual = lockfileForComparison(actualLock, options: options)
        if expected != actual {
            throw ConfigLockfileError.invalidLockfile(
                "replayed effective config does not match config lock: \(compactDiff(expected: expected, actual: actual))"
            )
        }
    }

    public static func configWithoutLockControls(_ config: ConfigValue) -> ConfigValue {
        guard case var .table(root) = config else {
            return config
        }
        guard case var .table(debug)? = root["debug"] else {
            return .table(root)
        }
        debug.removeValue(forKey: "config_lockfile")
        if debug.isEmpty {
            root.removeValue(forKey: "debug")
        } else {
            root["debug"] = .table(debug)
        }
        return .table(root)
    }

    private static func validateMetadataShape(_ lockfile: ConfigLockfile) throws {
        guard lockfile.version == configLockfileVersion else {
            throw ConfigLockfileError.invalidLockfile(
                "unsupported config lock version \(lockfile.version); expected \(configLockfileVersion)"
            )
        }
    }

    private static func lockfileForComparison(
        _ lockfile: ConfigLockfile,
        options: ConfigLockReplayOptions
    ) -> ConfigLockfile {
        var lockfile = lockfile
        lockfile.config = configWithoutLockControls(lockfile.config)
        if options.allowCodexVersionMismatch {
            lockfile.codexVersion = ""
        }
        return lockfile
    }

    private static func compactDiff(expected: ConfigLockfile, actual: ConfigLockfile) -> String {
        let expectedLines = renderedLockfile(expected).split(separator: "\n", omittingEmptySubsequences: false)
        let actualLines = renderedLockfile(actual).split(separator: "\n", omittingEmptySubsequences: false)
        if expectedLines == actualLines {
            return ""
        }
        return (["--- expected", "+++ actual"] + diffLines(expected: expectedLines, actual: actualLines))
            .joined(separator: "\n")
    }

    private static func renderedLockfile(_ lockfile: ConfigLockfile) -> String {
        ConfigTomlRenderer.render(.table([
            "version": .integer(Int64(lockfile.version)),
            "codex_version": .string(lockfile.codexVersion),
            "config": lockfile.config
        ]))
    }

    private static func diffLines(expected: [Substring], actual: [Substring]) -> [String] {
        let maxCount = max(expected.count, actual.count)
        var lines: [String] = []
        for index in 0..<maxCount {
            let left = index < expected.count ? String(expected[index]) : nil
            let right = index < actual.count ? String(actual[index]) : nil
            if left == right {
                if let left {
                    lines.append(" \(left)")
                }
            } else {
                if let left {
                    lines.append("-\(left)")
                }
                if let right {
                    lines.append("+\(right)")
                }
            }
        }
        return lines
    }
}
