#!/bin/sh
set -eu

package_directory=
output_path=

while [ "$#" -gt 0 ]; do
  case "$1" in
    --package-directory)
      shift
      package_directory=${1:-}
      ;;
    --output)
      shift
      output_path=${1:-}
      ;;
    *)
      echo "generate-build-metadata.sh: unexpected argument: $1" >&2
      exit 1
      ;;
  esac
  shift
done

if [ -z "$package_directory" ]; then
  echo "generate-build-metadata.sh: missing --package-directory" >&2
  exit 1
fi

if [ -z "$output_path" ]; then
  echo "generate-build-metadata.sh: missing --output" >&2
  exit 1
fi

first_non_empty() {
  for key in "$@"; do
    value=$(eval "printf '%s' \"\${$key:-}\"")
    if [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  done
  return 1
}

normalize_version() {
  raw=$1
  source=$2
  case "$raw" in
    v*) version=${raw#v} ;;
    *) version=$raw ;;
  esac
  if ! printf '%s' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z][0-9A-Za-z.-]*)?(\+[0-9A-Za-z][0-9A-Za-z.-]*)?$'; then
    echo "generate-build-metadata.sh: invalid Codex build version from $source: $raw" >&2
    exit 1
  fi
  printf '%s' "$version"
}

git_value() {
  tmpfile=$(mktemp "${TMPDIR:-/tmp}/codex-build-metadata.XXXXXX")
  if git -C "$package_directory" "$@" >"$tmpfile" 2>/dev/null; then
    value=$(tr -d '\n\r' <"$tmpfile")
    rm -f "$tmpfile"
    if [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  fi
  rm -f "$tmpfile"
  return 1
}

sanitize_identifier() {
  value=$(printf '%s' "$1" | LC_ALL=C tr -c '0-9A-Za-z-' '-')
  if [ -z "$value" ]; then
    printf 'unknown'
  else
    printf '%s' "$value"
  fi
}

sanitize_commit() {
  value=$(printf '%s' "$1" | LC_ALL=C tr -c '0-9A-Za-z._-' '-')
  if [ -z "$value" ]; then
    printf 'unknown'
  else
    printf '%s' "$value"
  fi
}

if explicit_version=$(first_non_empty CODEX_SWIFT_VERSION CODEX_VERSION); then
  version=$(normalize_version "$explicit_version" "environment")
  source=environment
elif [ -n "${GITHUB_REF_NAME:-}" ] && printf '%s' "$GITHUB_REF_NAME" | grep -Eq '^v?[0-9]+\.[0-9]+\.[0-9]+'; then
  version=$(normalize_version "$GITHUB_REF_NAME" "GITHUB_REF_NAME")
  source=github-ref
elif tag_version=$(git_value describe --tags --exact-match --match 'v[0-9]*' HEAD); then
  version=$(normalize_version "$tag_version" "git tag")
  source=git-tag
else
  short_commit=$(git_value rev-parse --short=12 HEAD || printf 'unknown')
  dirty=
  if [ -n "$(git -C "$package_directory" status --porcelain 2>/dev/null || true)" ]; then
    dirty=.dirty
  fi
  version="0.0.0-dev+$(sanitize_identifier "$short_commit")$dirty"
  source=git
fi

commit=$(first_non_empty CODEX_BUILD_COMMIT GITHUB_SHA || git_value rev-parse HEAD || printf 'unknown')
commit=$(sanitize_commit "$commit")

case "$version" in
  0.0.0|0.0.0-dev*) is_local_dev_build=true ;;
  *) is_local_dev_build=false ;;
esac

mkdir -p "$(dirname "$output_path")"
cat >"$output_path" <<EOF
// Generated by CodexBuildMetadataPlugin. Do not edit.

public enum CodexBuildMetadata {
    public static let version = "$version"
    public static let commit = "$commit"
    public static let source = "$source"
    public static let isLocalDevBuild = $is_local_dev_build
}

EOF
